name: messenger_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  encrypt: ^5.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  record: ^6.1.2
  audioplayers: ^6.1.1
  agora_rtc_engine: ^6.4.0
  permission_handler: ^11.3.1
  intl: ^0.20.2
  uuid: ^4.5.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  socket_io_client: ^3.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
